# Site settings
title: Bhavesh Pandey
# subtitle: Computer Graphics blog.
header-img: img/myimages/bhaveshpandey-vatican1.jpg
email: pandeybhavesh@gmail.com
copyright_name: Bhavesh Pandey
description: "Hi I am Bhavesh Pandey, a Visual Effects Technical Director crafting beautiful visual experiences for films and hollywood blockbusters. I have worked on blockbuster projects such as Wonder Woman 1984, Fantastic Beasts and Where to Find Them, Jurassic World Fallen Kingdom, Disney's The Jungle Book and many more!"
baseurl: ""
url: "https://bhaveshpandey.github.io"
twitter_username: bhaveshpandey
github_username:  bhaveshpandey

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: 'UA-103571322-1'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]
