# Site settings
title: Bhavesh Pandey
# subtitle: Computer Graphics blog.
header-img: img/home-bg.jpg
email: pandeybhavesh@gmail.com
copyright_name: Bhavesh Pandey
description: "Ramblings of a Computer Graphics technical director."
baseurl: ""
url: "https://bhaveshpandey.github.io"
twitter_username: bhaveshpandey
github_username:  bhaveshpandey

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
